### PR TITLE
merge to adrem1

### PR DESCRIPTION
**Pull request by adrem1**

### CODE REVIEW

**Comment by adrem1** [comment]
Hi everyone!

I am a bit lost here, and I'll just try to make a few mentions to see if I can please get some advice. @katomm, I am trying to merge my fork with the current version of the Foundation's master. It tells me there is a conflict in stake-pool-guide/getting-started/install.md. If I remember right, this is the file I had modified and turned out to be redundant. The system asks me to intervene with the command line but I have no idea how. Is there a way for me to delete my fork and create a new one? Do you have any suggestions?

Cheers,

A

**Comment by katomm** [comment]
Hello, please look into this: https://www.earthdatascience.org/courses/intro-to-earth-data-science/git-github/github-collaboration/update-github-repositories-with-changes-by-others/

**Comment by adrem1** [comment]
@katomm thank you for linking the guide. I have found the desktop version and was able to resolve conflicts generated by missing and new files. Thank you!

A

**Comment by adrem1** [comment]
Hi Tommy,

I hope this email finds you well. I have started versioning a guide for
complete newcomer delegators to Cardano (eg heard of crypto but don't know
how to get it).

At present this is a gitbook syncing to a private repo. When i have a final
first draft, i would like to make the lot public and will welcome input
from the community. Would you like to provide some feedback?

Cheers,

A

**Pull request merged**
